import os
import json
import argparse
from datetime import datetime
import config
import agent
from schemas import MeetingNotes
from orchestrator import MeetingOrchestrator

# Ensure directories exist
os.makedirs("data/samples", exist_ok=True)
os.makedirs("data/processed", exist_ok=True)

def export_to_markdown(notes: MeetingNotes, output_path: str):
    """
    Saves a beautifully formatted Markdown report of the meeting notes.
    """
    md_content = f"""# {notes.title}

* **Date:** {notes.date}
* **Attendees:** {', '.join(notes.attendees)}
* **Generated By:** EchoScribe Meeting Notes Agent ({"Mock Simulator" if config.MOCK_MODE else "Gemini API"})

---

## Executive Summary
{notes.summary}

---

## Key Decisions
"""
    if notes.decisions:
        for d in notes.decisions:
            md_content += f"- 💡 {d}\n"
    else:
        md_content += "*No major decisions recorded.*\n"

    md_content += "\n## Action Items\n"
    if notes.action_items:
        for item in notes.action_items:
            status_box = "[ ]" if item.status.lower() == "pending" else "[x]"
            assignee_str = f" @{item.assignee}" if item.assignee else ""
            deadline_str = f" (Due: {item.deadline})" if item.deadline else ""
            md_content += f"- {status_box} **{item.text}**{assignee_str}{deadline_str}\n"
    else:
        md_content += "*No action items assigned.*\n"

    md_content += "\n## Detailed Transcript\n"
    if notes.transcript:
        for seg in notes.transcript:
            m = int(seg.timestamp // 60)
            s = int(seg.timestamp % 60)
            ts = f"{m:02d}:{s:02d}"
            md_content += f"**[{ts}] {seg.speaker}**: {seg.text}\n\n"
    else:
        md_content += "*Transcript not available.*\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)

def handle_process(args):
    """
    Loads a transcript file, processes it via the Orchestrator, and saves all outputs.
    """
    file_path = args.file
    if not os.path.exists(file_path):
        print(f"Error: File '{file_path}' does not exist.")
        return

    print(f"Reading transcript: {file_path}")
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    print(f"Running meeting notes orchestrator pipeline using template '{args.template}'...")
    if config.MOCK_MODE:
        print("⚠️  No GEMINI_API_KEY detected in .env. Running in Offline Mock Mode...")
    
    def cli_confirm_email(to: str, subject: str, body: str) -> bool:
        print(f"\n--- 📧 PROPOSED EMAIL DRAFT ---")
        print(f"To:      {to}")
        print(f"Subject: {subject}")
        print(f"Body Snippet:\n{body[:350]}...")
        print(f"-------------------------------")
        try:
            choice = input("Confirm: Do you want to save/send this email draft? [y/N]: ").strip().lower()
            return choice in ["y", "yes"]
        except (KeyboardInterrupt, EOFError):
            return False

    def cli_confirm_calendar(title: str, attendees: list, date: str, description: str) -> bool:
        print(f"\n--- 📅 PROPOSED CALENDAR EVENT ---")
        print(f"Title:       {title}")
        print(f"Date:        {date}")
        print(f"Attendees:   {', '.join(attendees)}")
        print(f"Description: {description}")
        print(f"---------------------------------")
        try:
            choice = input("Confirm: Do you want to schedule this calendar event? [y/N]: ").strip().lower()
            return choice in ["y", "yes"]
        except (KeyboardInterrupt, EOFError):
            return False

    try:
        orchestrator = MeetingOrchestrator()
        pipeline_output = orchestrator.run_pipeline(
            transcript_text=text,
            template=args.template,
            confirm_email_callback=cli_confirm_email,
            confirm_calendar_callback=cli_confirm_calendar
        )
        notes = pipeline_output.meeting_notes
        
        # Create a unique ID/filename
        timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c for c in notes.title if c.isalnum() or c in (" ", "_", "-")).rstrip()
        safe_title = safe_title.replace(" ", "_").lower()
        meeting_id = f"meeting_{timestamp_str}_{safe_title}"

        # Save all orchestrator files (JSON, Email text, Tickets markdown)
        orchestrator.save_outputs(pipeline_output, "data/processed", meeting_id)

        # Save the standard readable markdown notes file
        md_path = f"data/processed/{meeting_id}.md"
        export_to_markdown(notes, md_path)

        print("\n✅ Pipeline Completed Successfully!")
        print(f"Meeting ID: {meeting_id}")
        print(f"Title:      {notes.title}")
        print(f"Summary:    {notes.summary[:80]}...")
        print(f"Files saved:")
        print(f"  - Full Pipeline Dataset (JSON):  data/processed/{meeting_id}.json")
        print(f"  - Meeting Notes Report (MD):     {md_path}")
        print(f"  - Project Tickets Export (MD):   data/processed/{meeting_id}_tickets.md")
        print(f"  - Email Summary Draft (TXT):     data/processed/{meeting_id}_email.txt")
        print(f"  - Calendar Follow-up (MD):       data/processed/{meeting_id}_calendar.md")
        print(f"\nYou can chat with this meeting by running: python main.py chat --meeting-id {meeting_id}")

    except Exception as e:
        print(f"❌ Error processing meeting pipeline: {e}")

def handle_list(args):
    """
    Lists all processed meeting notes.
    Supports both direct MeetingNotes JSON and nested OrchestratorOutput JSON.
    """
    processed_dir = "data/processed"
    files = [f for f in os.listdir(processed_dir) if f.endswith(".json")]
    
    if not files:
        print("No processed meetings found. Use 'python main.py process --file <file>' to add one.")
        return

    print(f"{'Meeting ID':<35} | {'Meeting Title':<30} | {'Date':<12} | {'Action Items':<12}")
    print("-" * 98)
    for filename in sorted(files):
        path = os.path.join(processed_dir, filename)
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
                meeting_id = filename[:-5] # strip .json
                
                # Check for nested model in orchestrator format vs flat meeting notes format
                notes_data = data.get("meeting_notes", data)
                title = notes_data.get("title", "Untitled")
                date = notes_data.get("date", "")[:10]
                actions_count = len(notes_data.get("action_items", []))
                
                # Truncate title for spacing
                if len(title) > 28:
                    title = title[:25] + "..."
                print(f"{meeting_id:<35} | {title:<30} | {date:<12} | {actions_count:<12}")
        except Exception as e:
            # Skip output files that may be formatted differently
            pass

def handle_chat(args):
    """
    Launches an interactive chat loop about a specific meeting.
    Supports both direct MeetingNotes JSON and nested OrchestratorOutput JSON.
    """
    meeting_id = args.meeting_id
    json_path = f"data/processed/{meeting_id}.json"

    if not os.path.exists(json_path):
        matching_files = [f for f in os.listdir("data/processed") if meeting_id in f and f.endswith(".json")]
        if matching_files:
            json_path = os.path.join("data/processed", matching_files[0])
            meeting_id = matching_files[0][:-5]
        else:
            print(f"Error: Meeting ID '{meeting_id}' not found.")
            return

    with open(json_path, "r", encoding="utf-8") as f:
        notes_dict = json.load(f)
        
        # Load inner MeetingNotes if data is an OrchestratorOutput
        inner_dict = notes_dict.get("meeting_notes", notes_dict)
        notes = MeetingNotes.model_validate(inner_dict)

    print(f"\n=======================================================")
    print(f"💬 Chatting with Agent about: {notes.title}")
    print(f"Summary: {notes.summary}")
    print(f"Attendees: {', '.join(notes.attendees)}")
    print(f"=======================================================")
    print("Type 'exit', 'quit', or 'q' to end the chat session.\n")

    history = []
    while True:
        try:
            user_msg = input("\nYou > ")
            if user_msg.strip().lower() in ["exit", "quit", "q"]:
                print("Ending chat session. Goodbye!")
                break
            
            if not user_msg.strip():
                continue

            print("Thinking...")
            response = agent.chat_with_meeting(notes, history, user_msg)
            print(f"\nAgent > {response}")

            # Append to history
            history.append({"role": "user", "text": user_msg})
            history.append({"role": "model", "text": response})

        except KeyboardInterrupt:
            print("\nEnding chat session. Goodbye!")
            break
        except Exception as e:
            print(f"\nError in chat: {e}")

def main():
    parser = argparse.ArgumentParser(description="EchoScribe AI - Meeting Notes Agent CLI")
    subparsers = parser.add_subparsers(dest="command", required=True, help="Sub-commands")

    # 'process' command
    process_parser = subparsers.add_parser("process", help="Process raw text transcript into meeting notes")
    process_parser.add_argument("--file", "-f", required=True, help="Path to raw transcript text file")
    process_parser.add_argument(
        "--template", "-t", 
        choices=["general", "standup", "brainstorm", "demo"], 
        default="general", 
        help="Styling template focus (default: general)"
    )

    # 'list' command
    subparsers.add_parser("list", help="List all processed meetings")

    # 'chat' command
    chat_parser = subparsers.add_parser("chat", help="Start an interactive chat session referencing meeting context")
    chat_parser.add_argument("--meeting-id", "-id", required=True, help="Unique ID of the processed meeting")

    args = parser.parse_args()

    if args.command == "process":
        handle_process(args)
    elif args.command == "list":
        handle_list(args)
    elif args.command == "chat":
        handle_chat(args)

if __name__ == "__main__":
    main()
